### ISSUE TITLE
Resolve problems with current math in SwerveModule class

### ISSUE THREAD

**Issue by tylerscheuble** [team2517/2015FRC#9]
What we have does not working. We need to debate stealing last year's code because this one is not working for various reasons.
@DirectHit999X

**Comment by admalledd** [comment]
Have you checked and read through the swerve math PDF and white paper?

https://github.com/team2517/2014FRC/blob/master/docs/swerveMath.pdf

It seems in your current code you are missing a lot of the edge-case protections that were written in the 2014 code...

**Comment by ironowl-txw** [comment]
Edge case protection?

On Sat, Feb 14, 2015 at 12:25 PM, Eric Driggers notifications@github.com
wrote:

> Have you checked and read through the swerve math PDF and white paper?
> 
> https://github.com/team2517/2014FRC/blob/master/docs/swerveMath.pdf
> 
> It seems in your current code you are missing a lot of the edge-case
> protections that were written in the 2014 code...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/team2517/2015FRC/issues/9#issuecomment-74390542.

## 

Sent from Mars because screw logic

**Comment by tylerscheuble** [comment]
The PDF tells us a bit about why a lot of these things are what they are, but since the 2014 code lacks comments we are having a hard time figuring out exactly what these calculations are and why we need them.

**Comment by admalledd** [comment]
see the for-loop here: https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L296

mostly I see missing OFFSETS, and some wrong error bounding I think.

Let me look at some of the older code, I will see about making a dump-doc on what is going on while I sit here at work waiting for servers to not die.

**Comment by tylerscheuble** [comment]
Offsets are something we are saving for when we have code that is at a state where we can control the motors because right now whenever we run code the motors seem to do their own thing including making the wheel spin forward at full speed and turn with very little control from the joystick. 

But if you could make a sort of dump doc we would appreciate that very much!

**Comment by admalledd** [comment]
working on it.

**Comment by admalledd** [comment]
2014 Swerve Drive code walk through

Most of the swerve code is isolated in one file at this check-in: [ref file](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp). I will link to specific lines and snippets within this doc

# [Get Input Data](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L169-L259)

Get all input data (joystick, buttons) and calculate center of robot

## [Joystick raw data](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L173-L180)

Get the joystick data and limit it to a "circle" with magnatude 1, else if you are in full top-left for example you would have a magnatude of 1.414~. Ignore most of the RAW(X/Y), we don't use those. Get `phi` which is our rotation speed.

## ["Locked" Force translation](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L181-L209)

If the driver is pressing some of these buttons force some of how the robot translates.
- [Button 5](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L181-L184): increase max locked translation speed
- [Button 4](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L190-L194): move only in +Y
- [Button 3](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L195-L199): move only in +X
- [Button 2](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L200-L204): move only in -Y
- [Button 1](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L205-L209): move only in -X

## [Center of Rotation](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L212-L249)

Change where the center of rotation is, aka where the robot thinks the center of mass is. See comments for which one is which. Defaults to actual center of robot. These are just the angles that the wheels are at relative to center of rotation.

## [Add left stick translations](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L251-L258)

Add what the left stick input is requesting (this means buttons are addative!)

# [Numbers!](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L260-L345)

Bulk of the calculations

## [Clean and Clamp Input data](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L260-L275)

Make sure our translation magnatudes are never greater than one, scale all others down to match what the new max is.

## [Calculate target angles](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L277-L285)

## [Get current angles](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L287-L290)

## [Calculate angle difference](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L292-L345)
- [Make sure DiffTheta is within 2PI](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L296-L303)
- [If we are far enough away, just reverse the motors](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L305-L314)
- [Calculate turn motor power](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L316)
- [Make sure turn power is not too low](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L318-L329)
- [set flags for if we had to reverse turn motor](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L330-L336)
- [Use above flags to make sure we don't go from full forward to full reverse and kill the motor](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L337-L344)

# [Set motors and staggar](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L362-L391)

## [set motor speeds, set to 0 if joysticks are 0](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L362-L374)

## [Set previous values to the now stale/used ones](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L376-L397)

## [Staggar so that only one module ran at a time](https://github.com/team2517/2014FRC/blob/22c6fa4573a1394dc6d8948443c2caeba3b71810/MyRobot.cpp#L381-L391)

**Comment by admalledd** [comment]
Note that in that specific code chunk it seems the staggar module stuff was not 100% done yet, so feel free to ignore kinda how those were working.

**Comment by cosmiccricket** [comment]
Hey there guys, I noticed a bunch of notifications popping up in my email from this org, and I'd like to help out if possible. If it wouldn't take too much time, and if you guys need more help, it would be great if someone could fill me in on why the code isn't working.

DISCLAIMER: I don't know that much about the Java side of FRC programming, but yeah, the offer is there.

**Comment by tylerscheuble** [comment]
@admalledd 
Thanks for that! We were using a flow chart that we wrote on a whiteboard previously but this sums it up much better. Although at least for now we are ignoring the staggering of the updates and the "locked" translation.

@cosmiccricket 
Sure! The code currently isn't working very well because our current programmers aren't completely familiar with how to write the code for swerve drive (2 motors for each wheel, one for rotation and other for movement) and we were left behind some C++ code from last year, so we are trying to write new code for maths we don't really understand very well since both of our programmers are on their second year and trigonometry is one year of math ahead of me. We are not only changing the language from C++ to Java this year, but we are also writing code for the new roboRIO which doesn't require that many actual changes in the code itself 
(you can get a porting guide here: https://wpilib.screenstepslive.com/s/4485/m/13809/l/292213-c-java-porting-guide-2014-to-2015), but we are also required to use a completely different IDE (WindRiver -> Eclipse). 

If you want to help out you are more than welcome to brush up on the code and comment on issues with ideas or recommendations, or email me at thetitantyler@gmail.com.

**Comment by admalledd** [comment]
The staggering code was because the CRIO did not really have enough CPU nor enough CAN bus bandwidth. the RoboRIO should have plenty and you can ignore it unless you need it.

Locked translation was a feature request from the drivers and IIRC not used too much in comp after they learned how to drive better :P

**Comment by cosmiccricket** [comment]
So is the math behind the swerve drive the biggest problem? Or is it something else? It looks like you aren't able to use last year's code for whatever reason. Is this an issue with porting from C++ to Java? It would also help to know what the swerve drive is currently doing versus what you guys need it to do, and how it looks on the robot.

I apologize if I am asking a lot of questions, the team website and Facebook page don't seem to be updated anymore. Maybe my man Eric already has everything under control?

**Comment by admalledd** [comment]
@cosmiccricket alas my work has kept me away from the team far too much this build season.

**Comment by tylerscheuble** [comment]
@cosmiccricket 
The math behind the swerve drive is the biggest problem but only because we are rewriting the code to where instead of doing everything on one file we want to separate all of the maths related to swerve (with exception of input methods) into relevant swerve classes as shown in this high quality diagram I just made in MS Paint.
![swervediagram](https://cloud.githubusercontent.com/assets/5944807/6204754/18bed250-b50b-11e4-9de2-4fb24147fcbc.png)
Note that we currently are doing a ton of repetitive calculations in the SwerveController but that is only because we are scrambling for working code. We plan to clean this up later.

**Comment by cosmiccricket** [comment]
Oh wow, I see stop build day is on the 17th. Does the team have a 2nd drive base that you can test code on like I had in 2013?

**Comment by tylerscheuble** [comment]
We don't have a second robot but we have a test board with 2 working swerve modules we have been running code on since if 2 modules are functioning then 4 should also work since it is going to be as simple as uncommenting the other 2 modules.

As of now the code seems to be almost fine but it lacks calibration and seems to constantly shift the movement wheel (mag variable) forward and backward

**Comment by gint271** [comment]
I don't know if you know this, but the team is allowed six hours to work on the robot after it has been bagged.  They could keep the modules out to test, and then attach them during the six hours.

**Comment by tylerscheuble** [comment]
@gint271 
I wish we could keep the modules out and attach them during the 6 hours but we don't have another roboRIO to run the code on and the code is incompatible with the cRIO. We also can't leave the electrical board out because otherwise it is technically not part of the robot.

**Comment by tylerscheuble** [comment]
The code seems to be working well now that we have stopped reversing the target angle after calculations! Leaving this open because people seem to be discussing things on here.

**Comment by cosmiccricket** [comment]
good to hear things were straightened out over there. good luck at competition!

**Comment by tylerscheuble** [comment]
@cosmiccricket 
Thanks! We aren't going to have much time to have much time to test so I am hoping for the best! :)
